#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-sparsevctrs
Version  : 0.3.1
Release  : 4
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/sparsevctrs_0.3.1.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/sparsevctrs_0.3.1.tar.gz
Summary  : Sparse Vectors for Use in Data Frames
Group    : Development/Tools
License  : MIT
Requires: R-sparsevctrs-lib = %{version}-%{release}
Requires: R-cli
Requires: R-rlang
Requires: R-vctrs
BuildRequires : R-cli
BuildRequires : R-rlang
BuildRequires : R-vctrs
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Representations for R Objects) that behave like regular vectors, and
    can thus be used in data frames. Also provides tools to convert
    between sparse matrices and data frames with sparse columns and
    functions to interact with sparse vectors.

%package lib
Summary: lib components for the R-sparsevctrs package.
Group: Libraries

%description lib
lib components for the R-sparsevctrs package.


%prep
%setup -q -n sparsevctrs

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742479381

%install
export SOURCE_DATE_EPOCH=1742479381
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/sparsevctrs/DESCRIPTION
/usr/lib64/R/library/sparsevctrs/INDEX
/usr/lib64/R/library/sparsevctrs/LICENSE
/usr/lib64/R/library/sparsevctrs/Meta/Rd.rds
/usr/lib64/R/library/sparsevctrs/Meta/features.rds
/usr/lib64/R/library/sparsevctrs/Meta/hsearch.rds
/usr/lib64/R/library/sparsevctrs/Meta/links.rds
/usr/lib64/R/library/sparsevctrs/Meta/nsInfo.rds
/usr/lib64/R/library/sparsevctrs/Meta/package.rds
/usr/lib64/R/library/sparsevctrs/Meta/vignette.rds
/usr/lib64/R/library/sparsevctrs/NAMESPACE
/usr/lib64/R/library/sparsevctrs/NEWS.md
/usr/lib64/R/library/sparsevctrs/R/sparsevctrs
/usr/lib64/R/library/sparsevctrs/R/sparsevctrs.rdb
/usr/lib64/R/library/sparsevctrs/R/sparsevctrs.rdx
/usr/lib64/R/library/sparsevctrs/doc/design.R
/usr/lib64/R/library/sparsevctrs/doc/design.Rmd
/usr/lib64/R/library/sparsevctrs/doc/design.html
/usr/lib64/R/library/sparsevctrs/doc/index.html
/usr/lib64/R/library/sparsevctrs/help/AnIndex
/usr/lib64/R/library/sparsevctrs/help/aliases.rds
/usr/lib64/R/library/sparsevctrs/help/figures/logo.png
/usr/lib64/R/library/sparsevctrs/help/paths.rds
/usr/lib64/R/library/sparsevctrs/help/sparsevctrs.rdb
/usr/lib64/R/library/sparsevctrs/help/sparsevctrs.rdx
/usr/lib64/R/library/sparsevctrs/html/00Index.html
/usr/lib64/R/library/sparsevctrs/html/R.css
/usr/lib64/R/library/sparsevctrs/tests/testthat.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/_snaps/coerce.md
/usr/lib64/R/library/sparsevctrs/tests/testthat/_snaps/sparse_character.md
/usr/lib64/R/library/sparsevctrs/tests/testthat/_snaps/sparse_double.md
/usr/lib64/R/library/sparsevctrs/tests/testthat/_snaps/sparse_dummy.md
/usr/lib64/R/library/sparsevctrs/tests/testthat/_snaps/sparse_integer.md
/usr/lib64/R/library/sparsevctrs/tests/testthat/_snaps/sparse_logical.md
/usr/lib64/R/library/sparsevctrs/tests/testthat/_snaps/sparsity.md
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-arithmatic.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-coerce-vector.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-coerce.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-extractors.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-has_sparse_elements.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_character.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_double.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_dummy.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_integer.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_is_na.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_lag.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_logical.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_mean.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_median.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_replace_na.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_sd.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_sqrt.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_var.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparse_which_na.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-sparsity.R
/usr/lib64/R/library/sparsevctrs/tests/testthat/test-type-predicates.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/sparsevctrs/libs/sparsevctrs.so
